#!/bin/sh
set -e

/usr/local/bin/base-docker-php-entrypoint

if [ ! -z "$DB_HOST" ]; then
    php bin/magento maintenance:enable
    php bin/magento deploy:mode:set production --skip-compilation
    php bin/magento app:config:import
    php bin/magento setup:upgrade --keep-generated
    php bin/magento cache:flush
    php bin/magento maintenance:disable
fi

"$@"
