#!/bin/sh

php -f /usr/local/bin/remove_redis_config.php

set -e
params="setup:config:set --cache-backend redis --cache-backend-redis-server ${DEFAULT_CACHE_REDIS_SERVER}"
if [ ! -z "$DEFAULT_CACHE_REDIS_PORT" ]; then
    params="$params --cache-backend-redis-port ${DEFAULT_CACHE_REDIS_PORT}"
fi
if [ ! -z "$DEFAULT_CACHE_REDIS_DATABASE" ]; then
    params="$params --cache-backend-redis-db ${DEFAULT_CACHE_REDIS_DATABASE}"
fi
if [ ! -z "$DEFAULT_CACHE_REDIS_PASSWORD" ]; then
    params="$params --cache-backend-redis-password ${DEFAULT_CACHE_REDIS_PASSWORD}"
fi

if [ ! -z "$DEFAULT_CACHE_REDIS_SERVER" ]; then
    bin/magento $params
fi

params="setup:config:set -n --page-cache=redis --page-cache-redis-server ${PAGE_CACHE_REDIS_SERVER}"
if [ ! -z "$PAGE_CACHE_REDIS_PORT" ]; then
    params="$params --page-cache-redis-port ${PAGE_CACHE_REDIS_PORT}"
fi
if [ ! -z "$PAGE_CACHE_REDIS_DATABASE" ]; then
    params="$params --page-cache-redis-db ${PAGE_CACHE_REDIS_DATABASE}"
fi
if [ ! -z "$PAGE_CACHE_REDIS_PASSWORD" ]; then
    params="$params --page-cache-redis-password ${PAGE_CACHE_REDIS_PASSWORD}"
fi
if [ ! -z "$PAGE_CACHE_REDIS_COMPRESS_DATA" ]; then
    params="$params --page-cache-redis-compress-data ${PAGE_CACHE_REDIS_COMPRESS_DATA}"
fi

if [ ! -z "$PAGE_CACHE_REDIS_SERVER" ]; then
    bin/magento $params
fi

params="setup:config:set -n --session-save redis --session-save-redis-host ${SESSION_REDIS_SERVER}"
if [ ! -z "$SESSION_REDIS_PORT" ]; then
    params="$params --page-cache-redis-port ${SESSION_REDIS_PORT}"
fi
if [ ! -z "$SESSION_REDIS_DATABASE" ]; then
    params="$params --page-cache-redis-db ${SESSION_REDIS_DATABASE}"
fi
if [ ! -z "$SESSION_REDIS_PASSWORD" ]; then
    params="$params --page-cache-redis-password ${SESSION_REDIS_PASSWORD}"
fi
if [ ! -z "$SESSION_REDIS_COMPRESS_DATA" ]; then
    params="$params --page-cache-redis-compress-data ${SESSION_REDIS_COMPRESS_DATA}"
fi
if [ ! -z "$SESSION_REDIS_TIMEOUT" ]; then
    params="$params --page-cache-redis-timeout ${SESSION_REDIS_TIMEOUT}"
fi
if [ ! -z "$SESSION_REDIS_PERSISTENT_IDENTIFIER" ]; then
    params="$params --page-cache-redis-persistent-id ${SESSION_REDIS_PERSISTENT_IDENTIFIER}"
fi
if [ ! -z "$SESSION_REDIS_COMPRESSION_THRESHOLD" ]; then
    params="$params --page-cache-redis-compression-threshold ${SESSION_REDIS_COMPRESSION_THRESHOLD}"
fi
if [ ! -z "$SESSION_REDIS_COMPRESSION_LIBRARY" ]; then
    params="$params --page-cache-redis-compression-lib ${SESSION_REDIS_COMPRESSION_LIBRARY}"
fi
if [ ! -z "$SESSION_REDIS_LOG_LEVEL" ]; then
    params="$params --page-cache-redis-log-level ${SESSION_REDIS_LOG_LEVEL}"
fi
if [ ! -z "$SESSION_REDIS_MAX_CONCURRENCY" ]; then
    params="$params --page-cache-redis-max-concurrency ${SESSION_REDIS_MAX_CONCURRENCY}"
fi
if [ ! -z "$SESSION_REDIS_BREAK_AFTER_FRONTEND" ]; then
    params="$params --page-cache-redis-break-after-frontend ${SESSION_REDIS_BREAK_AFTER_FRONTEND}"
fi
if [ ! -z "$SESSION_REDIS_BREAK_AFTER_ADMINHTML" ]; then
    params="$params --page-cache-redis-break-after-adminhtml ${SESSION_REDIS_BREAK_AFTER_ADMINHTML}"
fi
if [ ! -z "$SESSION_REDIS_FIRST_LIFETIME" ]; then
    params="$params --page-cache-redis-first-lifetime ${SESSION_REDIS_FIRST_LIFETIME}"
fi
if [ ! -z "$SESSION_REDIS_BOT_FIRST_LIFETIME" ]; then
    params="$params --page-cache-redis-bot-first-lifetime ${SESSION_REDIS_BOT_FIRST_LIFETIME}"
fi
if [ ! -z "$SESSION_REDIS_BOT_LIFETIME" ]; then
    params="$params --page-cache-redis-bot-lifetime ${SESSION_REDIS_BOT_LIFETIME}"
fi
if [ ! -z "$SESSION_REDIS_DISABLE_LOCKING" ]; then
    params="$params --page-cache-redis-disable-locking ${SESSION_REDIS_DISABLE_LOCKING}"
fi
if [ ! -z "$SESSION_REDIS_MIN_LIFETIME" ]; then
    params="$params --page-cache-redis-min-lifetime ${SESSION_REDIS_MIN_LIFETIME}"
fi
if [ ! -z "$SESSION_REDIS_MAX_LIFETIME" ]; then
    params="$params --page-cache-redis-max-lifetime ${SESSION_REDIS_MAX_LIFETIME}"
fi
if [ ! -z "$SESSION_REDIS_SENTINEL_MASTER" ]; then
    params="$params --page-cache-redis-sentinel-master ${SESSION_REDIS_SENTINEL_MASTER}"
fi
if [ ! -z "$SESSION_REDIS_SENTINEL_SERVERS" ]; then
    params="$params --page-cache-redis-sentinel-servers ${SESSION_REDIS_SENTINEL_SERVERS}"
fi
if [ ! -z "$SESSION_REDIS_SENTINEL_VERIFY_MASTER" ]; then
    params="$params --page-cache-redis-sentinel-verify-master ${SESSION_REDIS_SENTINEL_VERIFY_MASTER}"
fi
if [ ! -z "$SESSION_REDIS_SENTINEL_CONNECT_RETIRES" ]; then
    params="$params --page-cache-redis-sentinel-connect-retires ${SESSION_REDIS_SENTINEL_CONNECT_RETIRES}"
fi

if [ ! -z "$SESSION_REDIS_SERVER" ]; then
    bin/magento $params
fi
