#!/usr/bin/env bash
# Write .env and docker secrets to the deploy directory on a server.
# Called by deploy workflows with environment variables from GitHub Secrets.
# Idempotent: overwrites existing files.
set -euo pipefail

DEPLOY_DIR="${DEPLOY_DIR:-/opt/magento2}"

mkdir -p "$DEPLOY_DIR/docker/secrets"

###############################################################################
# .env file
###############################################################################

cat > "$DEPLOY_DIR/.env" <<EOF
# Auto-generated by deploy workflow — do not edit manually
export DOCKER_RESTART_POLICY=unless-stopped

# Admin
export BACKEND_FRONTNAME=${BACKEND_FRONTNAME}
export ADMIN_EMAIL=${ADMIN_EMAIL}
export ADMIN_FIRSTNAME=${ADMIN_FIRSTNAME}
export ADMIN_LASTNAME=${ADMIN_LASTNAME}
export TRANS_EMAIL_NAME=${TRANS_EMAIL_NAME}
export TRANS_EMAIL_ADDRESS=${TRANS_EMAIL_ADDRESS}

# SMTP
export SMTP_TRANSPORT=${SMTP_TRANSPORT}
export SMTP_HOST=${SMTP_HOST}
export SMTP_PORT=${SMTP_PORT}
export SMTP_USERNAME=${SMTP_USERNAME}
export SMTP_AUTH=${SMTP_AUTH}
export SMTP_SSL=${SMTP_SSL}

# Database
export DB_USER=${DB_USER}
export DB_NAME=${DB_NAME}

# OpenSearch
export OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}

# Caddy / TLS
export CADDY_EMAIL=${CADDY_EMAIL}
export DOMAIN=${DOMAIN}
EOF

###############################################################################
# Docker secrets (password files)
###############################################################################

echo -n "${DB_PASSWORD}"         > "$DEPLOY_DIR/docker/secrets/db_password.txt"
echo -n "${DB_PASSWORD}"         > "$DEPLOY_DIR/docker/secrets/mysql_password.txt"
echo -n "${MYSQL_ROOT_PASSWORD}" > "$DEPLOY_DIR/docker/secrets/mysql_root_password.txt"
echo -n "${ADMIN_PASSWORD}"      > "$DEPLOY_DIR/docker/secrets/admin_password.txt"
echo -n "${SMTP_PASSWORD}"       > "$DEPLOY_DIR/docker/secrets/smtp_password.txt"

# Restrict permissions
chmod 600 "$DEPLOY_DIR/docker/secrets/"*.txt
chmod 600 "$DEPLOY_DIR/.env"

echo "Environment and secrets written to $DEPLOY_DIR"
