#!/usr/bin/env bash
# Generate .env and docker secrets from config.toml + GitHub Secrets.
# Usage: ENV=staging|production ./infra/setup-env.sh
#
# - Reads infra/config.toml for non-secret values
# - Resolves ${SECRET_NAME} placeholders from environment variables (GitHub Secrets)
# - Staging inherits from production for any missing values
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$SCRIPT_DIR/config.toml"
DEPLOY_DIR="${DEPLOY_DIR:-/opt/magento2}"
ENV="${ENV:?ENV must be set to 'staging' or 'production'}"

mkdir -p "$DEPLOY_DIR/docker/secrets"

###############################################################################
# Parse config.toml and resolve values
###############################################################################

resolve_config() {
  python3 <<PYEOF
import tomllib, os, re, sys

with open("$CONFIG", "rb") as f:
    config = tomllib.load(f)

env = "$ENV"

def get(section, key):
    """Get value: try env-specific first, fall back to production."""
    val = None
    # Try environment-specific
    if env in config and section in config[env]:
        val = config[env][section].get(key)
    # Fall back to production
    if val is None and "production" in config and section in config["production"]:
        val = config["production"][section].get(key)
    if val is None:
        return ""
    # Resolve \${SECRET_NAME} placeholders from environment
    def replace_secret(m):
        secret_name = m.group(1)
        secret_val = os.environ.get(secret_name, "")
        if not secret_val:
            print(f"WARNING: Secret {secret_name} not found in environment", file=sys.stderr)
        return secret_val
    val = str(val)
    val = re.sub(r'\$\{(\w+)\}', replace_secret, val)
    return val

# Get domain from servers section
domain = config.get("servers", {}).get(env, {}).get("domain", "")
if not domain:
    domain = config.get("servers", {}).get("production", {}).get("domain", "")

# Output as shell variables
print(f'BACKEND_FRONTNAME={get("admin", "backend_frontname")}')
print(f'ADMIN_EMAIL={get("admin", "email")}')
print(f'ADMIN_FIRSTNAME={get("admin", "firstname")}')
print(f'ADMIN_LASTNAME={get("admin", "lastname")}')
print(f'ADMIN_PASSWORD={get("admin", "password")}')
print(f'TRANS_EMAIL_NAME={get("email", "trans_name")}')
print(f'TRANS_EMAIL_ADDRESS={get("email", "trans_address")}')
print(f'SMTP_TRANSPORT={get("email", "smtp_transport")}')
print(f'SMTP_HOST={get("email", "smtp_host")}')
print(f'SMTP_PORT={get("email", "smtp_port")}')
print(f'SMTP_USERNAME={get("email", "smtp_username")}')
print(f'SMTP_PASSWORD={get("email", "smtp_password")}')
print(f'SMTP_AUTH={get("email", "smtp_auth")}')
print(f'SMTP_SSL={get("email", "smtp_ssl")}')
print(f'DB_USER={get("database", "user")}')
print(f'DB_NAME={get("database", "name")}')
print(f'DB_PASSWORD={get("database", "password")}')
print(f'MYSQL_ROOT_PASSWORD={get("database", "root_password")}')
print(f'OPENSEARCH_PASSWORD={get("opensearch", "password")}')
print(f'CADDY_EMAIL={get("tls", "caddy_email")}')
print(f'DOMAIN={domain}')
PYEOF
}

###############################################################################
# Write .env
###############################################################################

RESOLVED=$(resolve_config)

{
  echo "# Auto-generated by setup-env.sh — do not edit manually"
  echo "# Environment: $ENV"
  echo "export DOCKER_RESTART_POLICY=unless-stopped"
  while IFS='=' read -r key value; do
    echo "export $key=$value"
  done <<< "$RESOLVED"
} > "$DEPLOY_DIR/.env"

###############################################################################
# Write docker secrets
###############################################################################

get_val() {
  echo "$RESOLVED" | grep "^$1=" | cut -d= -f2-
}

echo -n "$(get_val DB_PASSWORD)"         > "$DEPLOY_DIR/docker/secrets/db_password.txt"
echo -n "$(get_val DB_PASSWORD)"         > "$DEPLOY_DIR/docker/secrets/mysql_password.txt"
echo -n "$(get_val MYSQL_ROOT_PASSWORD)" > "$DEPLOY_DIR/docker/secrets/mysql_root_password.txt"
echo -n "$(get_val ADMIN_PASSWORD)"      > "$DEPLOY_DIR/docker/secrets/admin_password.txt"
echo -n "$(get_val SMTP_PASSWORD)"       > "$DEPLOY_DIR/docker/secrets/smtp_password.txt"

chmod 600 "$DEPLOY_DIR/docker/secrets/"*.txt
chmod 600 "$DEPLOY_DIR/.env"

echo "✅ Environment and secrets written to $DEPLOY_DIR (env: $ENV)"
