#!/bin/sh
set -e

while [ ! -f app/etc/env.php ]
do
  echo "Waiting for Magento installation to be started..."
  sleep 30
done

while [ -z "$(php -r """echo (include 'app/etc/env.php')['install']['date'];""")" ]
do
  echo "Waiting for Magento to be installed..."
  sleep 30
done

DB_HOST=$(php -r "echo (include 'app/etc/env.php')['db']['connection']['default']['host'];")

until nc -z -v -w30 $DB_HOST 3306
do
  echo "Waiting for database connection..."
  sleep 30
done

su magento -s /bin/sh -c 'set_database_config'
su magento -s /bin/sh -c 'set_redis_config'
# If command errors try to flush the redis cache
su magento -s /bin/sh -c 'bin/magento -n cron:remove' || redis-cli -h ${DEFAULT_CACHE_REDIS_SERVER} flushall && su magento -s /bin/sh -c 'bin/magento -n cron:remove'
su magento -s /bin/sh -c 'bin/magento -n cron:install'

"$@"
