#!/bin/sh
set -e

sed -i \
"s/\/\* {{ host }} \*\//${BACKEND_HOST}/g; \
s/\/\* {{ port }} \*\//${BACKEND_PORT}/g; \
s/\/\* {{ ips }} \*\//\"${VARNISH_HOST}\"\;/g; \
s/\/\* {{ ssl_offloaded_header }} \*\//${SSL_OFFLOADED_HEADER}/g; \
s/\/\* {{ design_exceptions_code }} \*\//${DESIGN_EXCEPTIONS_CODE}/g; \
s/\/\* {{ grace_period }} \*\//${GRACE_PERIOD}/g" \
/usr/local/etc/varnish/varnish-template.vcl

cp /usr/local/etc/varnish/varnish-template.vcl /usr/local/etc/varnish/default.vcl

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- varnishd "$@"
fi

# allow the container to be started with `--user`
if [ "$1" = 'varnishd' ] && [ "$(id -u)" = '0' ]; then
	chown -R varnish:varnish .
fi

exec "$@"
