#!/bin/sh
set -e

/usr/local/bin/base-docker-php-entrypoint

if [ ! -z "$DB_HOST" ]; then
  
    until nc -z -v -w30 $DB_HOST 3306
    do
      echo "Waiting for database connection..."
      sleep 30
    done
    su magento -s /bin/sh -c 'bin/magento maintenance:enable'
    su magento -s /bin/sh -c 'bin/magento deploy:mode:set production --skip-compilation'
    su magento -s /bin/sh -c 'bin/magento app:config:import'
    su magento -s /bin/sh -c 'bin/magento setup:upgrade --keep-generated'
    su magento -s /bin/sh -c 'bin/magento cache:flush'
    su magento -s /bin/sh -c 'bin/magento maintenance:disable'
fi

"$@"
