#!/bin/sh
set -e

DB_HOST=""
if [ -f app/etc/env.php ] && [ ! -z "$(php -r """echo (include 'app/etc/env.php')['db']['connection']['default']['host'];""")" ]; then
    DB_HOST=$(php -r "echo (include 'app/etc/env.php')['db']['connection']['default']['host'];")
fi
if [ ! -z "$MYSQL_HOST" ]; then
    DB_HOST=${MYSQL_HOST}
fi

if [ ! -z "$DB_HOST" ]; then
  
    until nc -z -v -w30 $DB_HOST 3306
    do
      echo "Waiting for database connection..."
      sleep 30
    done
    su magento -s /bin/sh -c 'set_database_config'
    su magento -s /bin/sh -c 'set_redis_config'
    su magento -s /bin/sh -c 'bin/magento maintenance:enable'
    su magento -s /bin/sh -c 'bin/magento deploy:mode:set production --skip-compilation'
    su magento -s /bin/sh -c 'bin/magento app:config:import'
    su magento -s /bin/sh -c 'bin/magento setup:upgrade --keep-generated'
    su magento -s /bin/sh -c 'bin/magento cache:flush'
    su magento -s /bin/sh -c 'bin/magento maintenance:disable'
fi

"$@"
